/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 06 15:54:29 GMT 2021
 */

package main;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import main.Account;
import main.Application;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Application_ESTest extends Application_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Application application0 = new Application();
      Account account0 = application0.account;
      account0.interest = 36500;
      application0.nextYear();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Application application0 = new Application();
      application0.account.balance = 36500;
      application0.nextDay();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Application application0 = new Application();
      Account account0 = new Account();
      application0.account = account0;
      application0.account = null;
      // Undeclared exception!
      try { 
        application0.nextYear();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.Application", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Application application0 = new Application();
      application0.account = null;
      // Undeclared exception!
      try { 
        application0.nextDay();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.Application", e);
      }
  }
}
